{
    "E000": "This code indicates an error occurred that does not match any of the categories defined. IT action at McKesson is required to resolve the issue.",
    "E011": "This code indicates an invalid User Name, Password or Initiative ID.",
    "E012": "This code indicates one or more tag names submitted was incorrect.",
    "E013": "This code indicates that an invalid data type was submitted.",
    "E014": "This code indicates that an invalid value was submitted for Q_CAM_ID.",
    "E101": "This code indicates one or more fields required for processing is missing.",
    "E139": "This code indicates invalid value for ZIP CODE",
    "E137": "This code indicates invalid value for State",
    "E311": "Invalid Contact Method",
    "E401": "This code indicates one or more answer values required for processing is missing or invalid.",
    "E402": "This code indicates an incorrect date format was passed.",
    "E403": "This code indicates a field length validation failed.",
    "E404": "This code indicates a non-numeric value was passed for a field which only accepts numeric values.",
    "E405": "Invalid Value for Q_INDICATION ",
    "E502": "This code indicates the card ID is already active.",
    "E503": "This code indicates the card ID is not valid for the program.",
    "E508": "Card ID is valid and patient does not have a card already. Allow patient to Activate/Enroll.",
    "E511": "This code indicates the patient failed our standard eligibility checks and is not eligible to activate/enroll into the program.  No further activation/enrollment action should be allowed with this patient.",
    "E541": "More than one record was found in the system matching the patient's identifying information.  This patient should be assisted by a live agent in the Customer Service Unit. ",
    "S540": "All validations have passed and the patient was successfully activated/enrolled. (or) this patient was found but with a different card id already associated to them.",
    "S550": "Successfully updated",
    "S718": "This code indicates an invalid answer value for Q_GENDER",
    "S731": "Email validation failed.",
}
